### PR TITLE
DLS-9855: [SDIL] Ensure adequate test coverage exists for SDIL Variations Repos - Non Controller

### PR DESCRIPTION
**Pull request by drewmiley**

### CODE REVIEW

**Comment by drewmiley** [comment]
Screenshot 2024-01-30 at 14 16 00
Currently up to 91.61%

**Comment by drewmiley** [comment]
Up to 91.78%
Screenshot 2024-01-30 at 16 38 58

**Comment by drewmiley** [comment]
Need to add/improve tests for all Site summary files (as mentioned in TODOs)

**Comment by drewmiley** [comment]
Also move summary test (+ app?) files to consistent folder structure

**Comment by drewmiley** [comment]
Up to 92.60%
Screenshot 2024-01-31 at 18 50 57

**Comment by drewmiley** [comment]
TODO: 

- Rebase,
- Add final case for NavigatiorForCorrectReturn,
- Add tests for UKSitesSummary (Correct Return)

**Comment by drewmiley** [comment]
Up to 93.05%
Screenshot 2024-02-01 at 11 45 15

**Comment by drewmiley** [comment]
Up to 93.67%
Screenshot 2024-02-01 at 15 33 26

**Review by JayenKerai — APPROVED** [review]

**Pull request merged**
